image: node:14.15.1

pipelines:
  branches:
    "{test,staging,master}":
      - step:
          caches:
            - node
          name: Trigger Backend Deploy
          script:
            - pipe: atlassian/trigger-pipeline:4.1.5
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                REPOSITORY: $BACKEND_REPOSITORY
                BRANCH_NAME: $BITBUCKET_BRANCH
    development:
      - step:
          caches:
            - sonar
            - node
          name: Perform Sonar Verifications
          script:
            - npm install
            - npm run lint
            - if [ ! -e sonar-scanner-4.6.2.2472-linux ]; then curl --insecure -o sonar-scanner-4.6.2.2472-linux.zip -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip; fi
            - if [ ! -e sonar-scanner-4.6.2.2472-linux ]; then unzip sonar-scanner-4.6.2.2472-linux.zip; fi
            - ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner
definitions:
  caches:
    sonar: sonar-scanner-4.6.2.2472-linux
